<?php

namespace AppBundle\Repository;

/**
 * PriviledgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriviledgeRepository extends \Doctrine\ORM\EntityRepository
{
}
