# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    file_form:
        class: AppBundle\Form\FilesType
        public: true
        arguments:  ['@security.token_storage','@form.factory']
        tags:
            - { name: form.type }